version: '3'

#  To rebuild application and get changes in docker, do following:
#
#  ./gradlew clean; ./gradlew bootJar; docker-compose up --build -d tasks-service

services:
  tasks-service:
    build: .
    container_name: tasks-service
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - DB_HOST=db
      - DB_NAME=tasks
      - DB_USER=postgres
      - DB_PASS=postgres

  db:
    image: 'postgres:13.1-alpine'
    container_name: tasks-service-db
    ports:
      - 5432:5432
    volumes:
      - tasks-service-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tasks

volumes:
  tasks-service-db:
    external: false
